import { InMemoryDbService } from 'angular-in-memory-web-api';


export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const foods = [
      { id: 1, name: 'food1', 
        ingredients: 'Egg, Rice, Sausage', 
        meal:'lunch', 
        tags:['high protein', 'low carb'], 
        kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
        url:  "../../assets/images/food-list/food1.png"},
      { id: 2, name: 'food2', 
        ingredients: 'Tofu, Rice, Soy Sauce', 
        meal:'lunch', 
        tags:['high protein', 'low carb', 'vegetarian'], 
        kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
        url:  "../../assets/images/food-list/food2.png" },
      { id: 3, name: 'food3', 
        ingredients: 'Egg, Rice, Sausage', 
        meal:'breakfast', 
        tags:['high protein', 'low carb'], 
        kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
        url:  "../../assets/images/food-list/food3.png" },
      { id: 4, name: 'food4', 
        ingredients: 'Egg, Rice, Sausage', 
        meal:'breakfast', 
        tags:['high protein', 'low carb'], 
        kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
        url:  "../../assets/images/food-list/food4.png" },
      { id: 5, name: 'food5', 
        ingredients: 'Egg, Rice, Sausage', 
        meal:'breakfast', 
        tags:['high protein', 'low carb'], 
        kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
        url:  "../../assets/images/food-list/food5.png" },
      { id: 6, name: 'food6', 
        ingredients: 'Egg, Rice, Sausage', 
        meal:'breakfast', 
        tags:['high protein', 'low carb'], 
        kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
        url:  "../../assets/images/food-list/food6.png" },
      { id: 7, name: 'food7', 
        ingredients: 'Egg, Rice, Sausage', 
        meal:'breakfast', 
        tags:['high protein', 'low carb'], 
        kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
        url:  "../../assets/images/food-list/food7.png" },
      { id: 8, name: 'food8', 
        ingredients: 'Egg, Rice, Sausage', 
        meal:'breakfast', 
        tags:['high protein', 'low carb'], 
        kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
        url:  "../../assets/images/food-list/food8.png" },
      { id: 9, name: 'food9', 
        ingredients: 'Egg, Rice, Sausage', 
        meal:'breakfast', 
        tags:['high protein', 'low carb'], 
        kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
        url:  "../../assets/images/food-list/food9.png" },
      { id: 10, name: 'food10', 
        ingredients: 'Egg, Rice, Sausage', 
        meal:'breakfast', 
        tags:['high protein', 'low carb'], 
        kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
        url:  "../../assets/images/food-list/food10.jpg" },
      { id: 11, name: 'food11', 
        ingredients: 'Egg, Rice, Sausage', 
        meal:'breakfast', 
        tags:['high protein', 'low carb'], 
        kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
        url:  "../../assets/images/food-list/food11.jpg" },
      { id: 12, name: 'food12', 
        ingredients: 'Egg, Rice, Sausage', 
        meal:'breakfast', 
        tags:['high protein', 'low carb'], 
        kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
        url:  "../../assets/images/food-list/food12.jpeg" },
      { id: 13, name: 'food13', 
        ingredients: 'Egg, Rice, Sausage', 
        meal:'breakfast', 
        tags:['high protein', 'low carb'], 
        kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
        url:  "../../assets/images/food-list/food13.jpg" },
      { id: 14, name: 'food14', 
        ingredients: 'Egg, Rice, Sausage', 
        meal:'breakfast', 
        tags:['high protein', 'low carb'], 
        kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
        url:  "../../assets/images/food-list/food14.jpg" },
        { id: 15, name: 'food15', 
        ingredients: 'Egg, Rice, Sausage', 
        meal:'breakfast', 
        tags:['high protein', 'low carb'], 
        kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
        url:  "../../assets/images/food-list/food15.jpg" },
        { id: 16, name: 'food16', 
        ingredients: 'Egg, Rice, Sausage', 
        meal:'breakfast', 
        tags:['high protein', 'low carb'], 
        kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
        url:  "../../assets/images/food-list/food16.jpg" },
        { id: 17, name: 'food17', 
        ingredients: 'Egg, Rice, Sausage', 
        meal:'breakfast', 
        tags:['high protein', 'low carb'], 
        kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
        url:  "../../assets/images/food-list/food17.jpg" },
        { id: 18, name: 'food18', 
        ingredients: 'Egg, Rice, Sausage', 
        meal:'breakfast', 
        tags:['high protein', 'low carb'], 
        kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
        url:  "../../assets/images/food-list/food18.jpg" },
        { id: 19, name: 'food19', 
        ingredients: 'Egg, Rice, Sausage', 
        meal:'breakfast', 
        tags:['high protein', 'low carb'], 
        kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
        url:  "../../assets/images/food-list/food19.png" },
        { id: 20, name: 'food20', 
          ingredients: 'Egg, Rice, Sausage', 
          meal:'breakfast', 
          tags:['high protein', 'low carb'], 
          kcal: 333, protein: 34, carbs: 12, fiber: 5, fat: 16,
          url:  "../../assets/images/food-list/food20.jpg" }
        

    ];
    return {foods};
  }
}